### ISSUE TITLE
Recommendation: Binder

### ISSUE THREAD

**Issue by ablekh** [pdonorio/cloudscale#4]
Hi Paolo,

If you're still interested in this/relevant topic (portable reproducible research workflows) and need/want to avoid messing with OpenStack (which I very much like, just think it might be an overkill for this use case), I would recommend you to take a look at open source project (and a public service) called Binder: http://mybinder.org. Currently, I'm working on deploying a local Binder instance for our software platform (we don't want to depend on - and overload - the public service as well as we want to have full control for the relevant infrastructure, including adding Jupyter kernels and such). Hope this helps (and sorry, if you're already aware of Binder :-) ).

Best regards,
Aleksandr

P.S. I ran across your profile via your EUDAT work (we plan to use iRODS to implement a data grid).

**Comment by pdonorio** [comment]
Hi @ablekh!
Thanks a ton for taking your time to talk about an open project on a similar problem.

I've encountered mybinder a little after this project was implemented and used. It's very cool! I've had some problems that time I made a test, and probably works better now. The key point with this repo was also to become capable of doing this kind of things, spawning containers and taking control. 

At this point Docker and third party app have grown so much that we are planning to work in some European project to create a service for deploying containers for our users and for us too. I'm being astonished by Rancher work so far, so I will probably prototype that one for the task in the near future.

p.s. where can I follow your work on the data grid with iRODS? Let me know if [our irods Docker images](https://hub.docker.com/u/eudatb2safe/) may help you too.

Best,
Paolo

**Comment by ablekh** [comment]
Hi @pdonorio ,

You are very welcome. Thank you for clarifying your experience with Binder as well as reminding me about your iRODS-related Docker images (I've seen them a while ago and starred those repos, planning to return to this aspect eventually). We will give them a try, even though it is too early to say whether we will use Docker technology for the data grid.

Speaking of iRODS-based data grid, we don't have anything open, simply because we don't have pretty much anything at all. In this aspect, we are in a very early stage; various functional and integration requirements complicate the matter. Nevertheless, I'm very optimistic (and very impressed by your and your EUDAT colleagues' work on the data grid) and definitely plan to share our experience and relevant code (when available - likely a while from now).

Let's stay in touch. Among others, I have a ResearchGate (RG) profile (https://www.researchgate.net/profile/Aleksandr_Blekh), where I maintain a description of a larger project (that I'm in charge of), which includes the data grid part. That description is supposed to get regular updates, but it is a hectic time now and in the near term... So, it is unlikely I will be posting anything of value any time soon. Anyway, please feel free to connect with me on RG, LinkedIn, etc. Skype and, even, good old e-mail work, too. :-)

Best,
Aleksandr
